version: '3'

services:
  translator:
    build: .
    volumes:
      - ./config:/app/config
      - ./input:/input    # Mount directory for input files
      - ./output:/output  # Mount directory for output files
    environment:
      - REDIS_URL=redis://redis:6379
      - CONFIG_PATH=/app/config/config.json
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"