---
services:
  translator:
    build: .
    volumes:
      - ./configs:/app/configs
      - /Volumes/External:/data
    environment:
      - CONFIG_PATH=/app/configs/config.json
      - DOCKER_ENV=true
