from PySubtitle.UnitTests.test_ChineseDinner import ChineseDinnerTests
from PySubtitle.UnitTests.test_localization import TestLocalization
from PySubtitle.UnitTests.test_Options import TestOptions
from PySubtitle.UnitTests.test_Options import TestSettingsHelpers
from PySubtitle.UnitTests.test_Options import TestSettingsType
from PySubtitle.UnitTests.test_Parse import TestParseDelayFromHeader, TestParseNames, TestParseValues
from PySubtitle.UnitTests.test_Substitutions import TestSubstitutions
from PySubtitle.UnitTests.test_Subtitles import TestSubtitles, SubtitleProcessorTests
from PySubtitle.UnitTests.test_Text import TestTextHelpers
from PySubtitle.UnitTests.test_Time import TestTimeHelpers
from PySubtitle.UnitTests.test_Translator import SubtitleTranslatorTests
